### ISSUE TITLE
Small compilation errors

### ISSUE THREAD

**Issue by OldWolf2** [giacomodrago/minijson_reader#1]
In commit 5ea1e3: Line 177 and 187: buffer_context_base should be detail::buffer_context_base
Line 468 and 504:  strtol and strtod should be std::strtol and std::strtod respectively.

**Comment by giacomodrago** [comment]
Hi, it should be fixed now in `c3f7ab`.

Out of curiosity, what compiler are you using?

**Comment by OldWolf2** [comment]
Hi

On 16/06/2015 6:36 p.m., Giacomo Drago wrote:
>
> Hi, it should be fixed now in |c3f7ab|.
>
> Out of curiosity, what compiler are you using?
>
>

This is with bcc32 6.70 (comes with C++Builder XE5).  A miserable excuse 
for a compiler, but minijson_reader seems to work correctly with those 
changes.   I'm a bit surprised that the code with "detail::" missing 
actually compiled in the mainstream compilers; there must be a lookup 
rule I'm unaware of.  The C++ standard does allow for "std::" being 
non-optional on std::strtol and std::strtod though.

Regards,
Matt.

**Comment by OldWolf2** [comment]
Hi again

I followed up, and it does look like a bcc32 bug that the versions 
without "detail::" were not accepted. Thanks for including it anyway :)

Regards,
Matt.

**Comment by giacomodrago** [comment]
A Borland C++ compiler: that explains many things ;)

Anyway I am glad I have fixed it for you. Give `minijson_writer` a go as well!
