### ISSUE TITLE
minijson_reader truncates strings containing a Unicode null character (\u0000)

### ISSUE THREAD

**Issue by michaelkourlas** [giacomodrago/minijson_reader#11]
When minijson_reader is used to parse a string containing a Unicode null character, such as "abc\u0000def", minijson_reader will interpret this as "abc".

I think this behaviour is insecure; minijson_reader should throw an exception instead.

**Comment by giacomodrago** [comment]
While I am not sure it is "insecure" as in causing memory corruption (if does, then it's probably an indication of an even deeper issue that should be solved as well - so scream even louder), I agree it should throw (with reason `INVALID_UTF16_CHARACTER` or a new `INVALID_UTF16_CHARACTER` to be added at the end of the enum). Again, if you come up with a PR I'll read it tomorrow together with the #9 one.

**Comment by michaelkourlas** [comment]
Sounds good!
