### ISSUE TITLE
Rework dispatch

### ISSUE THREAD

**Issue by giacomodrago** [giacomodrago/minijson_reader#16]
At the moment `minijson::dispatch` is a bit of a mess, not to mention a sheer abuse of operator overloading.

I would like to do something better (still under the constraint that it shouldn't allocate on the heap): ideally it should be able to (optionally) detect missing and/or unexpected fields and throw.

**Comment by giacomodrago** [comment]
This is done but it would benefit from a review (if not of the code, at least another point of view on the design). @michaelkourlas you have contributed before, you think you can help with this?

**Comment by michaelkourlas** [comment]
It's definitely a more fully featured API. I can see myself using the new functionality -- for example, the required vs. optional handlers. However, I don't think I'm in a good position to comment on the API design as such (and any problems with it, possible alternatives, etc.) without having used it in practice.

**Comment by giacomodrago** [comment]
Thank you! I myself used it and it does look fine. I'll merge (the main branch is the development one anyway) and wait for more feedback from other users (assuming there are!).
