### ISSUE TITLE
Determine if toplevel content is object or array

### ISSUE THREAD

**Issue by HighCommander4** [giacomodrago/minijson_reader#2]
If the top-level JSON content that I'm trying to parse can be either an array or an object, how do I tell which one it is? For nested content, I would use value::type(), but for the top-level content I don't have a value to call that on.

**Comment by giacomodrago** [comment]
I have trouble picturing a use case where you know so little about what you are parsing you don't even know if you're expecting an object or an array. Usually there are APIs with well-defined message formats, and at the very least you know whether the top-level entity is an object or an array.

After all, a rather unusual JSON library like this one is admittedly a pain in the neck for parsing entities you know little about. If you have such an elaborate use case, and you need flexibility, maybe you could go for a mainstream library that builds a model in memory, that you can query and manipulate as you please.

Maybe I could come up with a better design. Do you have a patch in mind (or in a branch)?

**Comment by HighCommander4** [comment]
> I have trouble picturing a use case where you know so little about what you are parsing you don't even know if you're expecting an object or an array. Usually there are APIs with well-defined message formats, and at the very least you know whether the top-level entity is an object or an array.

I can point you to an affected API in the wild.

It's a Canadian university's API for querying information about its courses. There is a call that gives you a list of "orgs", or departments, in the university:

> https://timetable.iit.artsci.utoronto.ca/api/orgs

and then you can make a call to query information about each org's list of courses:

> https://timetable.iit.artsci.utoronto.ca/api/courses?org=ANA

Now, most of these calls return an object, but if there are no courses, and empty array is returned:

> https://timetable.iit.artsci.utoronto.ca/api/courses?org=COL

I didn't design this API, and I probably wouldn't do it this way if I did, but I have to consume it.

> Maybe I could come up with a better design. Do you have a patch in mind (or in a branch)?

I had a mind a simple function `toplevel_value_type()` that returns the same thing that `value::type()` would return in a nested context.

**Comment by giacomodrago** [comment]
Oh my, there are some strange APIs out there! :sweat_smile:

But I didn't quite nail mine either. So, let me make an attempt at making the change you requested: thanks for the suggestion.

**Comment by giacomodrago** [comment]
I invented around your idea... I came up with a `parse_message()` function that returns a value, and then, depending on the `type()` of the value, you call `parse_object()` or `parse_array()`.

```
using namespace minijson;

char buf[] = "\n{\"foo\": \"bar\"}";
buffer_context ctx(buf, sizeof(buf) - 1);
value top = parse_message(ctx);
if (top.type() == Array)
{
    throw std::runtime_error("fail!");
}
else if (top.type() == Object)
{
    parse_object(ctx, [&](const char* k, value v)
    {
        dispatch (k)
        <<"foo">> [&]{ std::cout << v.as_string() << std::endl; };
    });
}
```

Some code is available in the `parse_message` branch, although **_I didn't test it carefully and it is not fit for production_**.

What do you think?

**Comment by HighCommander4** [comment]
Thanks for implementing this! I haven't had a chance to try it yet (traveling at the moment) but I will as soon as I do.

**Comment by HighCommander4** [comment]
I have tried `parse_message`, and it is working well. Thanks!

**Comment by giacomodrago** [comment]
OK, when I have some time I'll test it properly and merge it.

**Comment by HighCommander4** [comment]
Hi there! Any ETA on merging this change into the master branch?

**Comment by giacomodrago** [comment]
While I am not really proud of this library 😅 and I would write it very differently if I were to start from scratch, nevertheless I am trying to tidy up a couple of things (number parsing has top priority). Are you still interested in this `parse_message` thing, @HighCommander4 ? If not I will be closing this issue.

**Comment by HighCommander4** [comment]
@giacomodrago I've stopped maintaining the software that consumes the mentioned API a couple of years ago. The latest version does use your `parse_message` branch, and I think it's a sensible capability to have, but please feel free to prioritize accordingly and not spend more effort on this on my account.
