### ISSUE TITLE
parse_object issue

### ISSUE THREAD

**Issue by wonderzerg** [giacomodrago/minijson_reader#3]
I did an easy test to parse_object() on an json like: "{ \"firstName\":\"John\" , \"lastName\":\"Doe\" }".
it gives me a exception.
turns out that change the line 144, of minijson_read.hpp  from "m_read_offset++" to "++m_read_offset" will solve this ,
or should I just use a json string start with "\n"?

**Comment by giacomodrago** [comment]
Hi, sorry about that!
Can you please post a short, compilable program reproducing the problem? Thanks.

**Comment by giacomodrago** [comment]
Closing for now, as I need some code reproducing this. Feel free to add it when you have it.
