### ISSUE TITLE
License change request

### ISSUE THREAD

**Issue by endlisnis** [giacomodrago/minijson_reader#6]
I wanted to thank you for making such a useful project.  I have recently started using this project at work.

I was wondering if you would be willing to change the license to be one of the standard open source licenses?  I think the MIT license would most closely match your existing license.  Doing so would make it easier for me to use it at work.

**Comment by giacomodrago** [comment]
I remember the license I chose for this project is a 3-clause BSD, which is fairly standard and very permissible. It shouldn't cause any problems for commercial use or incompatibilities with other licenses. Anyway, I'll look into the MIT license.

**Comment by endlisnis** [comment]
Actually. Upon deeper investigation, it turns out that your existing license is fine.  Sorry for the noise.

**Comment by giacomodrago** [comment]
No worries.
