### ISSUE TITLE
minijson_reader does not distinguish between an unparsable value and a value parsable as zero

### ISSUE THREAD

**Issue by michaelkourlas** [giacomodrago/minijson_reader#9]
minijson_reader provides long and double representations of JSON numbers:

> long as_long(): the value as a long integer. This representation is available when type() is Number and the number could be parsed by strtol without overflows, or when the type is Boolean, in which case 1 or 0 are returned for true and false respectively. In all the other cases, 0 is returned.

> double as_double(): the value as a double-precision floating-point number. This representation is available when type() is Number and the number could be parsed by strtod without overflows or underflows, or when the type is Boolean, in which case non-zero or 0.0 are returned for true and false respectively. In all the other cases, 0.0 is returned.

The problem is that there’s no way to distinguish between 0 and “this value could not be parsed”.

I know there's a broader rework of number parsing in #4 being discussed, but as a short-term fix we can add `long_representation_available` and `double_representation_available` booleans.

**Comment by giacomodrago** [comment]
This library really **isn't** great, and if I were to rewrite it now from scratch it would look very different (but there are probably better alternatives around anyway, even respecting the same constraints e.g. no heap memory allocations).

#4 has been around for years, and I haven't had time to properly think about the problem of making number parsing less rubbish, nor did anyone come up in the meantime with a good solution ready for me to implement (or to just merge).

Given the context, I agree with your idea of adding those two bools to _at least_ solve this particular issue. The fastest way for you to have it done is, well, to issue a pull request. If you keep it single-topic, add the tests and the documentation, and make it easy to review, I'll merge it straightaway.

**Comment by michaelkourlas** [comment]
I'll be submitting a PR shortly!

**Comment by giacomodrago** [comment]
Hey @michaelkourlas, I went on a refactoring spree and reworked the `value` class entirely, on the `rework_number_parsing`. These `*_representation_available()` functions are no longer a thing because those representations are created lazily by calling `value.as<T>()` with `T` being an arithmetic type. `std::out_of_bounds` is thrown if the number does not fit in `T`.
